import GetContact from "@/components/Iletisim/GetContact";
import Haritalar from "@/components/Iletisim/Haritalar";
import Head from "next/head";
import React from "react";

const iletisim = () => {
  return (
    <>
      <Head>
        <title>Pengona Software</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className=" w-full mb-16 flex flex-col items-center justify-center ">
        <Haritalar/>
        <GetContact/>
      </main>
    </>
  );
};

export default iletisim;