import BilgilendirmeText from "@/components/Kurumsal/BilgilendirmeText";
import BiziTaniyin from "@/components/Kurumsal/BiziTaniyin";
import Politikalar from "@/components/Kurumsal/Politikalar";
import Head from "next/head";

export default function Kurumsal() {
  return (
    <>
      <Head>
        <title>Pengona Software</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className=" w-full mb-16 flex flex-col items-center justify-center ">
      {/* Hakkımızda Banner */}
        <h2 className="text-5xl my-8 font-bold">HAKKIMIZDA</h2>
        <BiziTaniyin/>
        <BilgilendirmeText/>
        <Politikalar/>
      </main>
    </>
  );
}