import React from 'react'

const BilgilendirmeText = () => {
  return (
    <div className='w-full lg:px-24 md:px-10 px-4 lg:py-24 md:py-12 py-6 flex flex-col text-[#000E36]  font-semibold '>
      <p className='text-xl'><span className='text-blue-400 text-3xl'>Vizyonumuz,</span> sektörde her zaman dinamik, üretken ve farklı olmaktır. Teknolojik gelişmelere hızla uyum sağlayarak müşterilerimize en iyi ve yenilikçi çözümleri sunmayı hedefliyoruz. Projelerimizi tam zamanında teslim ediyor ve müşterilerimizin işlerini kesintiye uğratmıyoruz. Ayrıca destek hizmetlerimizle müşterilerimizin her zaman yanında oluyor ve ihtiyaçlarına hızlı çözümler sunuyoruz.</p>
      <p className='text-xl mt-12 '><span className='text-blue-400 text-3xl '>Misyonumuz,</span> müşterilerimizin iş süreçlerini teknolojiyle yönetmelerine yardımcı olmak ve taleplerini hızlı bir şekilde karşılamaktır. Hosting hizmetimizle web sitelerinizi güvenli ve hızlı bir şekilde yayına alırken, domain hizmetimizle markanızı internete taşıyoruz. Web tasarım yazılımı ile modern ve kullanıcı dostu web siteleri oluştururken, Android/IOS mobil uygulama tasarım yazılımıyla müşterilerinizin mobil cihazlarda da etkili bir şekilde var olmanızı sağlıyoruz. Ayrıca portal hizmetimizle de iş süreçlerinizi kolayca yönetebilmenizi sağlıyoruz.</p>
      <p className='text-3xl text-blue-400 mt-14 '>Değerlerimiz</p>
      <p className='text-xl mt-12'><span className='font-bold'>Müşteri Odaklılık:&nbsp;</span>Müşterilerimizin ihtiyaçlarını anlamak ve onlara en iyi hizmeti sunmak için öncelikle müşterilerimizin beklentilerini ve taleplerini önemsiyoruz. Müşteri memnuniyetini her zaman en üst düzeyde tutmak için çabalıyor ve onların başarısını kendimize hedef olarak belirliyoruz.</p>
      <p className='text-xl mt-12'><span className='font-bold'>Kalite: &nbsp;</span>İşimizi tutkuyla yapıyor ve en yüksek kalite standartlarını benimseyerek müşterilerimize kaliteli çözümler sunuyoruz. Teknolojik gelişmeleri yakından takip ederek projelerimize yenilikçi ve özgün yaklaşımlar katıyor, müşterilerimize en iyi deneyimi yaşatmayı amaçlıyoruz.</p>
      <p className='text-xl mt-12'><span className='font-bold'>İnovasyon: &nbsp;</span>Teknolojik yenilikleri sürekli olarak takip ediyor ve projelerimize bu yenilikleri entegre ediyoruz. Sürekli öğrenme ve gelişme kültürünü benimsiyor, yaratıcı ve yenilikçi çözümler üreterek müşterilerimize rekabet avantajı sağlamayı hedefliyoruz.</p>
      <p className='text-xl mt-12'><span className='font-bold'>İşbirliği ve Ekip Çalışması: &nbsp;</span> Başarılı projelerin arkasında güçlü bir ekip çalışması yatar. Pengona Yazılım olarak, ekip üyelerimizin yeteneklerine değer veriyor ve farklı yetkinliklere sahip olan ekibimizle sinerji yaratıyoruz. İşbirliği ve iletişim odaklı çalışarak projelerimizi başarıyla tamamlıyoruz.</p>
      <p className='text-xl mt-12'><span className='font-bold'>Güvenilirlik: &nbsp;</span> Müşterilerimizin bize duyduğu güveni önemsiyor ve bu güveni korumak için gereken adımları atıyoruz. Söz verdiğimiz zamanlarda projeleri tamamlıyor, taahhütlerimize sadık kalıyor ve müşterilerimize güvenilir bir iş ortağı olduğumuzu kanıtlıyoruz.</p>
      <p className='text-xl mt-12'><span className='font-bold'>Sürdürülebilirlik: &nbsp;</span> Teknolojik çözümlerimizi, çevresel ve toplumsal sürdürülebilirlik ilkesini gözeterek tasarlıyoruz. Dijital dönüşüm süreçlerinde enerji verimliliği ve çevresel etkileri minimize etmek için çaba gösteriyoruz. Topluma katkı sağlamak ve sosyal sorumluluk bilinciyle hareket etmek önceliklerimiz arasında yer alıyor.</p>
    </div>
  )
}

export default BilgilendirmeText